name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    run_on: ubuntu_latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Goodbye!
