name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The name of the deployable artifact files'
        required: false
        default: 'dist-files'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying and uploading..."
