name: Container Deployment
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/s8-docker-deploy.yml'
      - 's8-docker-deploy/**'
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container: node:16
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017
      PORT: 8000
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        working-directory: s6-env-and-secrets
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
        working-directory: s6-env-and-secrets
      - name: Run tests
        run: npm test
        working-directory: s6-env-and-secrets
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_CLUSTER_ADDRESS: ${{ env.MONGODB_CLUSTER_ADDRESS }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"

