name: Custom Action
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/s9-custom-action.yml'
      - 's9-custom-action/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cache-deps
        with:
          caching: 'true'
      - name: Output information
        run: |
          echo "Cache used: ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Lint code
        working-directory: s9-custom-action
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cache-deps
      - name: Test code
        id: run-tests
        working-directory: s9-custom-action
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: s9-custom-action/test-report
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cache-deps
      - name: Build website
        working-directory: s9-custom-action
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: s9-custom-action/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run custom action
        id: custom-action
        uses: ./.github/actions/deploy-s3-javascript
        with:
          bucket: 'gha-custom-action-hosting'
          dist-folder: './dist'
          bucket-region: 'us-east-2'